import { Event } from "./types";

export const events: Event[] = [
  {
    id: "1",
    title: "Dalí. El enigma sin fin",
    venue: "Fundació Joan Miró",
    category: "exposición",
    description:
      "Un recorrido inmersivo por la mente surrealista de Salvador Dalí con más de 60 obras originales, incluyendo pinturas, dibujos y objetos surrealistas.",
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&h=500&fit=crop",
    startDate: "2026-03-15",
    endDate: "2026-07-30",
    price: 16,
    address: "Parc de Montjuïc, s/n",
    neighborhood: "Montjuïc",
    url: "https://www.fmirobcn.org",
    featured: true,
  },
  {
    id: "2",
    title: "Miró: Universos Paralelos",
    venue: "Fundació Joan Miró",
    category: "exposición",
    description:
      "Exposición que explora los mundos imaginarios de Miró a través de pinturas, esculturas y cerámicas nunca antes reunidas en una misma sala.",
    imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=500&fit=crop",
    startDate: "2026-04-01",
    endDate: "2026-09-15",
    price: 14,
    address: "Parc de Montjuïc, s/n",
    neighborhood: "Montjuïc",
    url: "https://www.fmirobcn.org",
    featured: false,
  },
  {
    id: "3",
    title: "Retratos del alma: de Klimt a Kahlo",
    venue: "MNAC",
    category: "exposición",
    description:
      "Una mirada íntima a los retratos más emocionales de la historia del arte. Desde el dorado de Klimt hasta la intensidad de Frida Kahlo.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=500&fit=crop",
    startDate: "2026-05-01",
    endDate: "2026-10-30",
    price: 12,
    address: "Palau Nacional, Parc de Montjuïc",
    neighborhood: "Montjuïc",
    url: "https://www.museunacional.cat",
    featured: true,
  },
  {
    id: "4",
    title: "Luz y color: del Impresionismo a la Abstracción",
    venue: "MACBA",
    category: "exposición",
    description:
      "Viaje visual desde los paisajes impresionistas de Monet hasta la geometría radical de Mondrian. Una exploración del color como lenguaje.",
    imageUrl: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&h=500&fit=crop",
    startDate: "2026-02-15",
    endDate: "2026-08-15",
    price: 11,
    address: "Plaça dels Àngels, 1",
    neighborhood: "El Raval",
    url: "https://www.macba.cat",
    featured: false,
  },
  {
    id: "5",
    title: "Maestros atemporales: de Vermeer a Picasso",
    venue: "Museu Picasso",
    category: "museo",
    description:
      "Diálogo entre los grandes maestros de la pintura. Un recorrido por las obras que cambiaron para siempre la historia del arte occidental.",
    imageUrl: "https://images.unsplash.com/photo-1572947650440-e8a97ef053b2?w=800&h=500&fit=crop",
    startDate: "2026-04-20",
    endDate: "2026-11-30",
    price: 12,
    address: "Carrer de Montcada, 15-23",
    neighborhood: "El Born",
    url: "https://www.museupicasso.bcn.cat",
    featured: false,
  },
  {
    id: "6",
    title: "Street to Gallery: Arte Urbano Contemporáneo",
    venue: "CCCB",
    category: "street art",
    description:
      "De Basquiat a Banksy: cómo el arte callejero conquistó los museos. Instalaciones interactivas, murales y obras originales.",
    imageUrl: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-12-15",
    price: 6,
    address: "Carrer de Montalegre, 5",
    neighborhood: "El Raval",
    url: "https://www.cccb.org",
    featured: true,
  },
  {
    id: "7",
    title: "Barcelona en 35mm",
    venue: "Foto Colectania",
    category: "fotografía",
    description:
      "Colección de fotografía analógica que retrata la Barcelona de los últimos 50 años a través de los ojos de fotógrafos locales e internacionales.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=500&fit=crop",
    startDate: "2026-05-10",
    endDate: "2026-09-30",
    price: 8,
    address: "Passeig de Picasso, 14",
    neighborhood: "El Born",
    url: "https://www.fotocolectania.org",
    featured: false,
  },
  {
    id: "8",
    title: "Cerámica y fuego: taller de Raku",
    venue: "Taller Gracia Arts",
    category: "taller",
    description:
      "Aprende la técnica japonesa Raku en un taller intensivo de 4 horas. Incluye materiales, horneado y pieza para llevar a casa.",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=500&fit=crop",
    startDate: "2026-05-17",
    endDate: "2026-05-17",
    price: 65,
    address: "Carrer de Verdi, 45",
    neighborhood: "Gràcia",
    url: "#",
    featured: false,
  },
  {
    id: "9",
    title: "Colección permanente Fundació Tàpies",
    venue: "Fundació Antoni Tàpies",
    category: "museo",
    description:
      "La obra esencial de Antoni Tàpies, uno de los artistas más importantes del arte contemporáneo catalán y español del siglo XX.",
    imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&h=500&fit=crop",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    price: 8,
    address: "Carrer d'Aragó, 255",
    neighborhood: "Eixample",
    url: "https://fundaciotapies.org",
    featured: false,
  },
  {
    id: "10",
    title: "Performance: Cuerpo y espacio",
    venue: "Arts Santa Mònica",
    category: "performance",
    description:
      "Ciclo de performances en vivo que exploran la relación entre el cuerpo humano y los espacios arquitectónicos. Artistas nacionales e internacionales.",
    imageUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&h=500&fit=crop",
    startDate: "2026-06-05",
    endDate: "2026-06-20",
    price: null,
    address: "La Rambla, 7",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "11",
    title: "Grabado contemporáneo: nuevas voces",
    venue: "Galería Marlborough",
    category: "galería",
    description:
      "Muestra colectiva de artistas emergentes que reinventan el grabado con técnicas mixtas, intervención digital y materiales no convencionales.",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=500&fit=crop",
    startDate: "2026-05-20",
    endDate: "2026-07-15",
    price: null,
    address: "Carrer d'Enric Granados, 68",
    neighborhood: "Eixample",
    url: "#",
    featured: false,
  },
  {
    id: "12",
    title: "Acuarela al aire libre en el Park Güell",
    venue: "BCN Art Walks",
    category: "taller",
    description:
      "Sesión guiada de pintura al aire libre en uno de los enclaves más icónicos de Gaudí. Todos los niveles. Material incluido.",
    imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=500&fit=crop",
    startDate: "2026-05-24",
    endDate: "2026-05-24",
    price: 40,
    address: "Park Güell, entrada Carmel",
    neighborhood: "Gràcia",
    url: "#",
    featured: false,
  },
];
