import { Event } from "./types";

/**
 * Mock events for June 2026 across all cultural categories.
 * Images from Unsplash — relevant to each activity.
 */
export const MOCK_EVENTS: Event[] = [
  // ── Arte / Exposiciones ───────────────────────────
  {
    id: "mock-1",
    title: "Miró: Constelaciones y Silencios",
    venue: "Fundació Joan Miró",
    category: "exposición",
    description: "Retrospectiva sobre la serie Constelaciones de Miró, con obras nunca expuestas en Barcelona.",
    imageUrl: "https://images.unsplash.com/photo-1545128485-c400e7702796?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-09-28",
    price: 16,
    address: "Parc de Montjuïc, s/n",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-2",
    title: "Picasso Azul: Los años de Barcelona",
    venue: "Museu Picasso",
    category: "museo",
    description: "Las obras del período azul de Picasso pintadas durante sus estancias en Barcelona.",
    imageUrl: "https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-10-15",
    price: 12,
    address: "Carrer Montcada, 15-23",
    neighborhood: "El Born",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-3",
    title: "MACBA Colección: Deconstrucciones",
    venue: "MACBA",
    category: "exposición",
    description: "La colección permanente del MACBA reinterpretada a través del concepto de deconstrucción.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-12-20",
    price: 11,
    address: "Plaça dels Àngels, 1",
    neighborhood: "El Raval",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-4",
    title: "Chez Matisse: Intimidad y Color",
    venue: "CaixaForum Barcelona",
    category: "exposición",
    description: "Un viaje por los interiores pintados por Matisse, con préstamos del Centre Pompidou.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-09-15",
    price: 6,
    address: "Av. Francesc Ferrer i Guàrdia, 6-8",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-5",
    title: "Banksy vs. Warhol",
    venue: "Moco Museum Barcelona",
    category: "exposición",
    description: "Confrontación visual entre dos iconos del arte pop y el street art.",
    imageUrl: "https://images.unsplash.com/photo-1531913764164-f85c3e01b2aa?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-08-30",
    price: 18,
    address: "Carrer de Montcada, 25",
    neighborhood: "El Born",
    url: "#",
    featured: false,
    tier: 1,
  },
  {
    id: "mock-6",
    title: "Románico 360°: Inmersión en el MNAC",
    venue: "MNAC",
    category: "museo",
    description: "Experiencia inmersiva en las salas de arte románico del MNAC con proyecciones digitales.",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-11-30",
    price: 12,
    address: "Palau Nacional, Parc de Montjuïc",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-7",
    title: "MEAM: Figuración Contemporánea",
    venue: "MEAM — Museu Europeu d'Art Modern",
    category: "museo",
    description: "Lo mejor del arte figurativo contemporáneo europeo en el palacio Gomis.",
    imageUrl: "https://images.unsplash.com/photo-1594794312433-05a69a98b7a0?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-07-31",
    price: 11,
    address: "Carrer de la Barra de Ferro, 5",
    neighborhood: "El Born",
    url: "#",
    featured: false,
    tier: 1,
  },
  {
    id: "mock-8",
    title: "IA y Creatividad",
    venue: "CCCB",
    category: "exposición",
    description: "Exploración del impacto de la IA en la creación artística contemporánea.",
    imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-09-28",
    price: 6,
    address: "Carrer de Montalegre, 5",
    neighborhood: "El Raval",
    url: "#",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-a10",
    title: "Galería Marlborough: Nuevas Miradas",
    venue: "Galería Marlborough Barcelona",
    category: "galería",
    description: "Colectiva de artistas emergentes catalanes seleccionados por la galería.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=500&fit=crop",
    startDate: "2026-06-02",
    endDate: "2026-06-30",
    price: null,
    address: "Carrer d'Enric Granados, 68",
    neighborhood: "L'Eixample",
    url: "#",
    featured: false,
  },

  // ── Talleres ──────────────────────────────────────
  {
    id: "mock-a9",
    title: "Taller de Cerámica Japonesa: Kintsugi",
    venue: "Espai Brossa",
    category: "taller",
    description: "Aprende la técnica del kintsugi en este taller inmersivo de fin de semana.",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=500&fit=crop",
    startDate: "2026-06-07",
    endDate: "2026-06-08",
    price: 35,
    address: "Carrer d'Allada-Vermell, 10",
    neighborhood: "El Born",
    url: "#",
    featured: false,
  },
  {
    id: "mock-w1",
    title: "Acuarela al aire libre en Ciutadella",
    venue: "Parc de la Ciutadella",
    category: "taller",
    description: "Taller de acuarela en el parque guiado por la artista Marina Solé. Todos los niveles.",
    imageUrl: "https://images.unsplash.com/photo-1533328818-4e19e4aa4288?w=800&h=500&fit=crop",
    startDate: "2026-06-14",
    endDate: "2026-06-14",
    price: 25,
    address: "Parc de la Ciutadella",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "mock-w2",
    title: "Grabado y Estampación",
    venue: "Taller de Gravat al Born",
    category: "taller",
    description: "Introducción a las técnicas de grabado artístico: punta seca, aguafuerte y linóleo.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=500&fit=crop",
    startDate: "2026-06-05",
    endDate: "2026-06-26",
    price: 40,
    address: "Carrer dels Flassaders, 22",
    neighborhood: "El Born",
    url: "#",
    featured: false,
  },
  {
    id: "mock-w3",
    title: "Fotografía nocturna por el Gótico",
    venue: "Miscelánea Gallery",
    category: "taller",
    description: "Ruta fotográfica nocturna por el Barri Gòtic. Trae tu cámara o móvil.",
    imageUrl: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=500&fit=crop",
    startDate: "2026-06-20",
    endDate: "2026-06-21",
    price: 30,
    address: "Carrer de la Guàrdia, 10",
    neighborhood: "El Raval",
    url: "#",
    featured: false,
  },
  {
    id: "mock-w4",
    title: "Lettering y Caligrafía Creativa",
    venue: "La Invisible BCN",
    category: "taller",
    description: "Workshop intensivo de lettering con brush pen y acuarela. Incluye materiales.",
    imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=500&fit=crop",
    startDate: "2026-06-12",
    endDate: "2026-06-12",
    price: 45,
    address: "Carrer del Peu de la Creu, 4",
    neighborhood: "El Raval",
    url: "#",
    featured: false,
  },
  {
    id: "mock-w5",
    title: "Taller de Cómic e Ilustración",
    venue: "Escola Joso",
    category: "taller",
    description: "Sesión abierta de cómic: del guión a la viñeta, con profesores de Joso.",
    imageUrl: "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=800&h=500&fit=crop",
    startDate: "2026-06-21",
    endDate: "2026-06-22",
    price: 20,
    address: "Carrer de la Ciutat, 6",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },

  // ── Teatro ────────────────────────────────────────
  {
    id: "mock-t1",
    title: "La Casa de Bernarda Alba",
    venue: "Teatre Nacional de Catalunya",
    category: "teatro",
    description: "El clásico de Lorca con dirección de Àlex Rigola y escenografía de Max Glaenzel.",
    imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-22",
    price: 28,
    address: "Plaça de les Arts, 1",
    neighborhood: "El Clot",
    url: "#",
    featured: true,
  },
  {
    id: "mock-t2",
    title: "Hamlet — Companyia T de Teatre",
    venue: "Teatre Lliure Montjuïc",
    category: "teatro",
    description: "Versión libre de Hamlet con actrices de la Companyia T de Teatre.",
    imageUrl: "https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=800&h=500&fit=crop",
    startDate: "2026-06-05",
    endDate: "2026-06-28",
    price: 24,
    address: "Plaça de Margarida Xirgu, 1",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
  },
  {
    id: "mock-t3",
    title: "Impro Barcelona: Noche de comedia",
    venue: "Sala Beckett",
    category: "teatro",
    description: "Show de improvisación con los mejores comediantes de la escena barcelonesa.",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&h=500&fit=crop",
    startDate: "2026-06-06",
    endDate: "2026-06-07",
    price: 15,
    address: "Carrer de Pere IV, 228-232",
    neighborhood: "Poblenou",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t4",
    title: "El Método Grönholm",
    venue: "Teatre Poliorama",
    category: "teatro",
    description: "La comedia de Jordi Galceran sobre entrevistas de trabajo despiadadas.",
    imageUrl: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-29",
    price: 22,
    address: "La Rambla, 115",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t5",
    title: "Terra Baixa — Àngel Guimerà",
    venue: "Teatre Romea",
    category: "teatro",
    description: "El drama rural catalán por excelencia, en una nueva producción del Romea.",
    imageUrl: "https://images.unsplash.com/photo-1516307365426-bea591f05011?w=800&h=500&fit=crop",
    startDate: "2026-06-10",
    endDate: "2026-07-05",
    price: 26,
    address: "Carrer de l'Hospital, 51",
    neighborhood: "El Raval",
    url: "#",
    featured: true,
  },
  {
    id: "mock-t6",
    title: "Dansa Barcelona: Companyia Gelabert",
    venue: "Mercat de les Flors",
    category: "danza",
    description: "La compañía de Cesc Gelabert presenta su última creación de danza contemporánea.",
    imageUrl: "https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?w=800&h=500&fit=crop",
    startDate: "2026-06-18",
    endDate: "2026-06-22",
    price: 18,
    address: "Carrer de Lleida, 59",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t7",
    title: "Antígona — versión de Pau Miró",
    venue: "Teatre Lliure Gràcia",
    category: "teatro",
    description: "Una Antígona contemporánea que traslada el conflicto clásico al presente.",
    imageUrl: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&h=500&fit=crop",
    startDate: "2026-06-12",
    endDate: "2026-06-30",
    price: 22,
    address: "Carrer de Montseny, 47",
    neighborhood: "Gràcia",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t8",
    title: "Circo Raluy: Temporada de verano",
    venue: "Carpa Raluy — Port Vell",
    category: "teatro",
    description: "El circo histórico de Barcelona abre su temporada estival en el Port Vell.",
    imageUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    price: 20,
    address: "Moll de la Fusta, s/n",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t9",
    title: "Monólogos en el Antic Teatre",
    venue: "Antic Teatre",
    category: "teatro",
    description: "Ciclo de monólogos de humor alternativo cada viernes de junio.",
    imageUrl: "https://images.unsplash.com/photo-1527979809431-ea3d5c0c01c9?w=800&h=500&fit=crop",
    startDate: "2026-06-06",
    endDate: "2026-06-27",
    price: 10,
    address: "Carrer de Verdaguer i Callís, 12",
    neighborhood: "Sant Pere",
    url: "#",
    featured: false,
  },
  {
    id: "mock-t10",
    title: "Ciclo de Cine al Aire Libre",
    venue: "Sala Montjuïc",
    category: "cine",
    description: "Proyecciones de clásicos bajo las estrellas en el Castell de Montjuïc.",
    imageUrl: "https://images.unsplash.com/photo-1587974928442-77dc3e0748ae?w=800&h=500&fit=crop",
    startDate: "2026-06-25",
    endDate: "2026-06-28",
    price: 7,
    address: "Castell de Montjuïc",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: false,
  },

  // ── Música ────────────────────────────────────────
  {
    id: "mock-m1",
    title: "Rosalía: Motomami World Tour",
    venue: "Palau Sant Jordi",
    category: "música",
    description: "Rosalía presenta su gira mundial con parada en Barcelona.",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop",
    startDate: "2026-06-14",
    endDate: "2026-06-15",
    price: 65,
    address: "Passeig Olímpic, 5-7",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m2",
    title: "Jazz al Palau: Brad Mehldau Trio",
    venue: "Palau de la Música Catalana",
    category: "música",
    description: "El pianista Brad Mehldau y su trío en el incomparable Palau de la Música.",
    imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=500&fit=crop",
    startDate: "2026-06-20",
    endDate: "2026-06-20",
    price: 45,
    address: "Carrer Palau de la Música, 4-6",
    neighborhood: "Sant Pere",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m3",
    title: "Sónar Festival 2026",
    venue: "Fira Montjuïc + Fira Gran Via",
    category: "festival",
    description: "El festival de referencia en música electrónica avanzada y arte digital.",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=500&fit=crop",
    startDate: "2026-06-18",
    endDate: "2026-06-20",
    price: 75,
    address: "Fira Montjuïc",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m4",
    title: "Nits d'Estiu al Castell de Montjuïc",
    venue: "Castell de Montjuïc",
    category: "música",
    description: "Ciclo de conciertos al aire libre con vistas panorámicas de Barcelona.",
    imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&h=500&fit=crop",
    startDate: "2026-06-20",
    endDate: "2026-06-28",
    price: 20,
    address: "Carretera de Montjuïc, 66",
    neighborhood: "Sants-Montjuïc",
    url: "#",
    featured: false,
  },
  {
    id: "mock-m5",
    title: "Primavera a les Fàbriques: Indie Night",
    venue: "Razzmatazz",
    category: "música",
    description: "Noche de bandas indie locales e internacionales en cinco salas.",
    imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&h=500&fit=crop",
    startDate: "2026-06-12",
    endDate: "2026-06-13",
    price: 18,
    address: "Carrer dels Almogàvers, 122",
    neighborhood: "Poblenou",
    url: "#",
    featured: false,
  },
  {
    id: "mock-m6",
    title: "OBC: Beethoven & Brahms",
    venue: "L'Auditori",
    category: "música",
    description: "La Orquestra Simfònica de Barcelona interpreta la 5ª de Beethoven y la 4ª de Brahms.",
    imageUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&h=500&fit=crop",
    startDate: "2026-06-06",
    endDate: "2026-06-08",
    price: 35,
    address: "Carrer de Lepant, 150",
    neighborhood: "El Clot",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m7",
    title: "Flamenco en el Tablao Cordobés",
    venue: "Tablao Flamenco Cordobés",
    category: "música",
    description: "Espectáculo de flamenco con los mejores bailaores y guitarristas.",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    price: 32,
    address: "La Rambla, 35",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "mock-m8",
    title: "Festival Jardins de Pedralbes",
    venue: "Jardins de Pedralbes",
    category: "festival",
    description: "Conciertos en los jardines del Palau Reial con artistas internacionales.",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=500&fit=crop",
    startDate: "2026-06-05",
    endDate: "2026-07-10",
    price: 45,
    address: "Av. Diagonal, 686",
    neighborhood: "Les Corts",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m9",
    title: "Jamboree Jazz Club: Jazz Night",
    venue: "Jamboree Jazz Club",
    category: "música",
    description: "Jazz en directo cada noche en el mítico club de Plaça Reial.",
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    price: 15,
    address: "Plaça Reial, 17",
    neighborhood: "Ciutat Vella",
    url: "#",
    featured: false,
  },
  {
    id: "mock-m10",
    title: "Cruïlla Festival 2026",
    venue: "Parc del Fòrum",
    category: "festival",
    description: "Uno de los grandes festivales de Barcelona: pop, rock, electrónica y world music.",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
    startDate: "2026-06-25",
    endDate: "2026-06-27",
    price: 60,
    address: "Parc del Fòrum",
    neighborhood: "Sant Martí",
    url: "#",
    featured: true,
  },
  {
    id: "mock-m11",
    title: "Maria Arnal i Marcel Bagés",
    venue: "Sala Apolo",
    category: "música",
    description: "El dúo catalán que fusiona tradición y electrónica presenta nuevo disco.",
    imageUrl: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&h=500&fit=crop",
    startDate: "2026-06-10",
    endDate: "2026-06-10",
    price: 22,
    address: "Carrer Nou de la Rambla, 113",
    neighborhood: "Poble-sec",
    url: "#",
    featured: false,
  },
  {
    id: "mock-m12",
    title: "Choir! Choir! Choir! Barcelona",
    venue: "Antiga Fàbrica Estrella Damm",
    category: "música",
    description: "Evento coral participativo: ven a cantar con cientos de personas.",
    imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=500&fit=crop",
    startDate: "2026-06-17",
    endDate: "2026-06-17",
    price: null,
    address: "Carrer del Rosselló, 515",
    neighborhood: "Sant Martí",
    url: "#",
    featured: false,
  },

  // ── Teatro — desde TeatreBarcelona.com ───────────
  {
    id: "mock-tb1",
    title: "Ànima",
    venue: "Teatre Tívoli",
    category: "teatro",
    description: "Espectáculo visual que fusiona danza, teatro y artes digitales en una experiencia inmersiva sobre la conexión humana.",
    imageUrl: "https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=800&h=500&fit=crop",
    startDate: "2026-02-27",
    endDate: "2026-06-24",
    price: 21,
    address: "Carrer de Casp, 8",
    neighborhood: "L'Eixample",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-tb2",
    title: "El Firmament",
    venue: "TNC — Sala Petita",
    category: "teatro",
    description: "Nueva creación en la Sala Petita del TNC. Teatro contemporáneo catalán de primer nivel.",
    imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=500&fit=crop",
    startDate: "2026-06-06",
    endDate: "2026-06-14",
    price: 14,
    address: "Plaça de les Arts, 1",
    neighborhood: "El Clot",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb3",
    title: "Permagel",
    venue: "Espai Texas",
    category: "teatro",
    description: "Obra sobre el deshielo y el cambio climático. Teatro que hace pensar en un espacio alternativo.",
    imageUrl: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&h=500&fit=crop",
    startDate: "2026-04-08",
    endDate: "2026-06-28",
    price: 28,
    address: "Carrer de la Cera, 14",
    neighborhood: "El Raval",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb4",
    title: "Perfectes desconeguts",
    venue: "Teatre Poliorama",
    category: "teatro",
    description: "Comedia sobre un grupo de amigos que deciden compartir todos los mensajes de sus móviles durante una cena.",
    imageUrl: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&h=500&fit=crop",
    startDate: "2026-03-13",
    endDate: "2026-06-07",
    price: 25,
    address: "La Rambla, 115",
    neighborhood: "Ciutat Vella",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb5",
    title: "El Gran Gatsby",
    venue: "Teatre Victòria",
    category: "teatro",
    description: "Adaptación teatral del clásico de F. Scott Fitzgerald. Los locos años 20 en el escenario.",
    imageUrl: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800&h=500&fit=crop",
    startDate: "2026-06-20",
    endDate: "2026-06-30",
    price: 28,
    address: "Av. del Paral·lel, 67",
    neighborhood: "Poble-sec",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-tb6",
    title: "Una idea genial",
    venue: "Teatre Condal",
    category: "teatro",
    description: "Comedia sobre la creatividad, las ideas absurdas y las decisiones que cambian una vida.",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&h=500&fit=crop",
    startDate: "2026-03-19",
    endDate: "2026-06-30",
    price: 22,
    address: "Av. del Paral·lel, 91",
    neighborhood: "Poble-sec",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb7",
    title: "Dinamarca",
    venue: "Sala Beckett — Sala de baix",
    category: "teatro",
    description: "Dramaturgia contemporánea en la Beckett. Teatro íntimo que incomoda y emociona.",
    imageUrl: "https://images.unsplash.com/photo-1516307365426-bea591f05011?w=800&h=500&fit=crop",
    startDate: "2026-06-15",
    endDate: "2026-06-14",
    price: 15,
    address: "Carrer de Pere IV, 228-232",
    neighborhood: "Poblenou",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb8",
    title: "Seis personajes en busca de autor",
    venue: "Teatre Apolo",
    category: "teatro",
    description: "El clásico de Pirandello que desdibuja la frontera entre ficción y realidad.",
    imageUrl: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=500&fit=crop",
    startDate: "2026-06-05",
    endDate: "2026-06-17",
    price: 15,
    address: "Av. del Paral·lel, 59",
    neighborhood: "Poble-sec",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb9",
    title: "Èdip & Antígona",
    venue: "TNC — Sala Gran",
    category: "teatro",
    description: "Los dos mitos griegos reunidos en la Sala Gran del Teatre Nacional. Tragedia clásica con dirección de primer nivel.",
    imageUrl: "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&h=500&fit=crop",
    startDate: "2026-04-22",
    endDate: "2026-06-30",
    price: 17,
    address: "Plaça de les Arts, 1",
    neighborhood: "El Clot",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-tb10",
    title: "Improshow",
    venue: "Teatreneu",
    category: "teatro",
    description: "Show de improvisación en el Teatreneu de Gràcia. Si no ríes, no pagas.",
    imageUrl: "https://images.unsplash.com/photo-1527979809431-ea3d5c0c01c9?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    price: 11,
    address: "Carrer de Terol, 26",
    neighborhood: "Gràcia",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb11",
    title: "La promesa",
    venue: "Teatre Borràs",
    category: "teatro",
    description: "Thriller psicológico sobre secretos familiares. Con actores de primer nivel de la escena catalana.",
    imageUrl: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&h=500&fit=crop",
    startDate: "2026-06-21",
    endDate: "2026-07-12",
    price: 23,
    address: "Plaça Urquinaona, 9",
    neighborhood: "L'Eixample",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb12",
    title: "Corta el cable rojo",
    venue: "Teatre Muntaner",
    category: "teatro",
    description: "Comedia interactiva donde el público decide el destino de los personajes. Cada función es distinta.",
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    price: 20,
    address: "Carrer de Muntaner, 4",
    neighborhood: "L'Eixample",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: false,
  },
  {
    id: "mock-tb13",
    title: "Mamma Mia!",
    venue: "Teatre Tívoli",
    category: "teatro",
    description: "El musical de ABBA llega a Barcelona. Canciones míticas y una historia que engancha.",
    imageUrl: "https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=800&h=500&fit=crop",
    startDate: "2026-09-26",
    endDate: "2026-11-29",
    price: 18,
    address: "Carrer de Casp, 8",
    neighborhood: "L'Eixample",
    url: "https://es.teatrebarcelona.com/cartelera-teatro-barcelona",
    featured: true,
    tier: 1,
  },

  // ── Jazz — desde jazz.barcelona ──────────────────
  {
    id: "mock-jz1",
    title: "Sullivan Fortner",
    venue: "Conservatori Liceu",
    category: "música",
    description: "Pianista de jazz ganador del Grammy. Solo piano en el Conservatori del Liceu.",
    imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=500&fit=crop",
    startDate: "2026-06-30",
    endDate: "2026-06-30",
    price: 25,
    address: "Carrer Nou de la Rambla, 82",
    neighborhood: "El Raval",
    url: "https://www.jazz.barcelona/es/proximos-conciertos",
    featured: false,
  },
  {
    id: "mock-jz2",
    title: "Van Morrison",
    venue: "Auditori Fòrum CCIB",
    category: "música",
    description: "La leyenda del soul, blues y jazz en Barcelona. Noche irrepetible.",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop",
    startDate: "2026-07-03",
    endDate: "2026-07-03",
    price: 65,
    address: "Plaça de Willy Brandt, 11-14",
    neighborhood: "Sant Martí",
    url: "https://www.jazz.barcelona/es/proximos-conciertos",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-jz3",
    title: "Pat Metheny Side-Eye III+",
    venue: "Palau de la Música Catalana",
    category: "música",
    description: "El guitarrista de jazz más influyente de su generación. Side-Eye en el Palau de la Música.",
    imageUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&h=500&fit=crop",
    startDate: "2026-07-23",
    endDate: "2026-07-23",
    price: 45,
    address: "Carrer Palau de la Música, 4-6",
    neighborhood: "Sant Pere",
    url: "https://www.jazz.barcelona/es/proximos-conciertos",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-jz4",
    title: "Marcus Miller: We Want Miles!",
    venue: "Palau de la Música Catalana",
    category: "música",
    description: "Marcus Miller rinde tributo a Miles Davis. Bajo eléctrico, funk y jazz de altísimo nivel.",
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop",
    startDate: "2026-07-24",
    endDate: "2026-07-24",
    price: 45,
    address: "Carrer Palau de la Música, 4-6",
    neighborhood: "Sant Pere",
    url: "https://www.jazz.barcelona/es/proximos-conciertos",
    featured: true,
    tier: 1,
  },
  {
    id: "mock-jz5",
    title: "Maria Schneider & Clasijazz Big Band",
    venue: "Paral·lel 62",
    category: "música",
    description: "La compositora de jazz con más Grammys de la historia dirige la Clasijazz Big Band con Antonio Lizana.",
    imageUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&h=500&fit=crop",
    startDate: "2026-07-13",
    endDate: "2026-07-13",
    price: 30,
    address: "Av. del Paral·lel, 62",
    neighborhood: "Poble-sec",
    url: "https://www.jazz.barcelona/es/proximos-conciertos",
    featured: false,
  },

  // ── Sala El Siglo — Sant Cugat ───────────────────
  {
    id: "mock-sg1",
    title: "Messenger Collective — Jazz Fusion",
    venue: "Sala El Siglo — Mercantic",
    category: "música",
    description: "Jazz fusión en directo en la Sala El Siglo dentro de Mercantic. Concierto vermut de sábado.",
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop",
    startDate: "2026-06-13",
    endDate: "2026-06-13",
    price: 12,
    address: "Av. de Rius i Taulet, 120, Sant Cugat del Vallès",
    neighborhood: "Sant Cugat",
    url: "https://www.salaelsiglo.com/",
    featured: false,
  },
  {
    id: "mock-sg2",
    title: "La Jam del Siglo",
    venue: "Sala El Siglo — Mercantic",
    category: "música",
    description: "Jam session abierta cada miércoles. Músicos locales y sorpresas cada semana.",
    imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=500&fit=crop",
    startDate: "2026-06-03",
    endDate: "2026-06-24",
    price: null,
    address: "Av. de Rius i Taulet, 120, Sant Cugat del Vallès",
    neighborhood: "Sant Cugat",
    url: "https://www.salaelsiglo.com/",
    featured: false,
  },
  {
    id: "mock-sg3",
    title: "El Siglo presenta: Aina Rabassa",
    venue: "Sala El Siglo — Mercantic",
    category: "música",
    description: "Aina Rabassa en concierto íntimo. Cantautora catalana con influencias de folk y jazz.",
    imageUrl: "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&h=500&fit=crop",
    startDate: "2026-06-28",
    endDate: "2026-06-28",
    price: 15,
    address: "Av. de Rius i Taulet, 120, Sant Cugat del Vallès",
    neighborhood: "Sant Cugat",
    url: "https://www.salaelsiglo.com/",
    featured: false,
  },

  // ── Aude — La Habitación Sonora ──────────────────
  {
    id: "mock-au1",
    title: "Aude Sessions: Escucha Activa",
    venue: "Aude — La Habitación Sonora",
    category: "música",
    description: "Listening room en Barcelona. Sesiones de escucha activa de lunes a miércoles con vinilos y sonido hi-fi en un espacio íntimo.",
    imageUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=500&fit=crop",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    price: 10,
    address: "Barcelona",
    neighborhood: "L'Eixample",
    url: "https://audelahabitacionsonora.com/",
    featured: false,
  },
];

/**
 * Get events for a specific date in the calendar
 */
export function getEventsForDate(date: Date): Event[] {
  const dateStr = date.toISOString().split("T")[0];
  return MOCK_EVENTS.filter((e) => {
    return dateStr >= e.startDate && dateStr <= e.endDate;
  });
}

/**
 * Get event counts by category filter for a given month
 */
export function getEventDatesForMonth(year: number, month: number): Map<string, { total: number; arte: number; musica: number; teatro: number }> {
  const counts = new Map<string, { total: number; arte: number; musica: number; teatro: number }>();
  const daysInMonth = new Date(year, month + 1, 0).getDate();

  for (let day = 1; day <= daysInMonth; day++) {
    const date = new Date(year, month, day);
    const dateStr = date.toISOString().split("T")[0];
    const eventsForDay = MOCK_EVENTS.filter(
      (e) => dateStr >= e.startDate && dateStr <= e.endDate
    );
    if (eventsForDay.length > 0) {
      let arte = 0, musica = 0, teatro = 0;
      for (const e of eventsForDay) {
        const cat = e.category;
        if (cat === "exposición" || cat === "museo" || cat === "galería" || cat === "taller") arte++;
        else if (cat === "música" || cat === "festival") musica++;
        else teatro++;
      }
      counts.set(dateStr, { total: eventsForDay.length, arte, musica, teatro });
    }
  }
  return counts;
}
