import { Venue } from "./types";

export const venues: Venue[] = [
  // ─── Poblenou / 22@ ───────────────────────────────────────────────
  {
    id: "v-pob-01",
    name: "Can Felipa",
    type: "centro cultural",
    neighborhood: "Poblenou / 22@",
    address: "Carrer de Pallars, 277",
    description: "Centro cívico con sala de exposiciones, teatro y talleres en una antigua fábrica textil.",
    url: "https://canfelipa.cat",
    tier: 2,
    lat: 41.3985,
    lng: 2.1988,
  },
  {
    id: "v-pob-02",
    name: "Razzmatazz",
    type: "sala de conciertos",
    neighborhood: "Poblenou / 22@",
    address: "Carrer dels Almogàvers, 122",
    description: "Macrosala con 5 espacios independientes. Referencia del circuito de música en vivo de Barcelona.",
    url: "https://www.salarazzmatazz.com",
    tier: 1,
    lat: 41.3975,
    lng: 2.1897,
  },
  {
    id: "v-pob-03",
    name: "Palo Alto Market",
    type: "espacio al aire libre",
    neighborhood: "Poblenou / 22@",
    address: "Carrer dels Pellaires, 30",
    description: "Mercado mensual de diseño, gastronomía y música en un recinto fabril reconvertido.",
    url: "https://pfrfrr.com",
    tier: 2,
    lat: 41.3960,
    lng: 2.1960,
  },
  {
    id: "v-pob-04",
    name: "La Plata",
    type: "bar",
    neighborhood: "Poblenou / 22@",
    address: "Rambla del Poblenou, 11",
    description: "Bar de barrio en la Rambla del Poblenou, perfecto para vermut y tapas caseras.",
    tier: 3,
    lat: 41.4005,
    lng: 2.2005,
  },
  {
    id: "v-pob-05",
    name: "Espai Nyam",
    type: "restaurante",
    neighborhood: "Poblenou / 22@",
    address: "Carrer de Pujades, 95",
    description: "Cocina de mercado y brunch de fin de semana en un espacio luminoso del 22@.",
    tier: 3,
    lat: 41.3975,
    lng: 2.1925,
  },
  {
    id: "v-pob-06",
    name: "Hangar",
    type: "sala de exposiciones",
    neighborhood: "Poblenou / 22@",
    address: "Carrer de Emília Coranty, 16",
    description: "Centro de producción e investigación en artes visuales. Residencias y exposiciones de artistas emergentes.",
    url: "https://hangar.org",
    tier: 2,
    lat: 41.4035,
    lng: 2.2095,
  },

  // ─── Gràcia ────────────────────────────────────────────────────────
  {
    id: "v-gra-01",
    name: "Cines Verdi",
    type: "cine",
    neighborhood: "Gràcia",
    address: "Carrer de Verdi, 32",
    description: "Cine de referencia en versión original subtitulada desde 1980. 9 salas.",
    url: "https://www.cines-verdi.com",
    tier: 1,
    lat: 41.4043,
    lng: 2.1569,
  },
  {
    id: "v-gra-02",
    name: "Teatre Lliure – Gràcia",
    type: "teatro",
    neighborhood: "Gràcia",
    address: "Carrer del Montseny, 47",
    description: "Sala histórica del Teatre Lliure. Programación de teatro contemporáneo y danza.",
    url: "https://www.teatrelliure.com",
    tier: 1,
    lat: 41.4018,
    lng: 2.1560,
  },
  {
    id: "v-gra-03",
    name: "Plaça del Sol",
    type: "espacio al aire libre",
    neighborhood: "Gràcia",
    address: "Plaça del Sol",
    description: "Plaza emblemática de Gràcia. Epicentro de la vida nocturna y terrazas del barrio.",
    tier: 2,
    lat: 41.4030,
    lng: 2.1567,
  },
  {
    id: "v-gra-04",
    name: "Bodega Cal Pep",
    type: "bar",
    neighborhood: "Gràcia",
    address: "Plaça de la Vila de Gràcia, 6",
    description: "Bodega tradicional junto a la torre del reloj. Vinos a granel y ambiente de barrio.",
    tier: 3,
    lat: 41.4020,
    lng: 2.1575,
  },
  {
    id: "v-gra-05",
    name: "La Pepita",
    type: "restaurante",
    neighborhood: "Gràcia",
    address: "Carrer de Còrsega, 343",
    description: "Tapas creativas en un local retro muy popular. Reserva imprescindible los fines de semana.",
    tier: 2,
    lat: 41.3990,
    lng: 2.1580,
  },
  {
    id: "v-gra-06",
    name: "Centre Artesà Tradicionàrius",
    type: "sala de conciertos",
    neighborhood: "Gràcia",
    address: "Travessia de Sant Antoni, 6",
    description: "Sala dedicada a la música tradicional y folk. Programación de raíz mediterránea.",
    url: "https://www.tradicionarius.cat",
    tier: 2,
    lat: 41.4010,
    lng: 2.1535,
  },
  {
    id: "v-gra-07",
    name: "Heliogàbal",
    type: "bar",
    neighborhood: "Gràcia",
    address: "Carrer de Ramón y Cajal, 80",
    description: "Bar cultural mítico de Gràcia: poesía, música experimental y performances en un sótano.",
    tier: 2,
    lat: 41.4048,
    lng: 2.1545,
  },

  // ─── El Born ───────────────────────────────────────────────────────
  {
    id: "v-born-01",
    name: "Museu Picasso",
    type: "museo",
    neighborhood: "El Born",
    address: "Carrer de Montcada, 15-23",
    description: "Colección permanente de más de 4.000 obras del período formativo y de madurez de Picasso.",
    url: "https://www.museupicasso.bcn.cat",
    tier: 1,
    lat: 41.3853,
    lng: 2.1813,
  },
  {
    id: "v-born-02",
    name: "El Born Centre de Cultura i Memòria",
    type: "centro cultural",
    neighborhood: "El Born",
    address: "Plaça Comercial, 12",
    description: "Antiguo mercado de hierro reconvertido en centro cultural con yacimiento arqueológico de 1714.",
    url: "https://elbornculturaimemoria.barcelona.cat",
    tier: 1,
    lat: 41.3855,
    lng: 2.1835,
  },
  {
    id: "v-born-03",
    name: "Paradiso",
    type: "bar",
    neighborhood: "El Born",
    address: "Carrer de Rera Palau, 4",
    description: "Speakeasy escondido detrás de una pastrami bar. Top 50 World's Best Bars.",
    tier: 1,
    lat: 41.3845,
    lng: 2.1825,
  },
  {
    id: "v-born-04",
    name: "MEAM (Museu Europeu d'Art Modern)",
    type: "museo",
    neighborhood: "El Born",
    address: "Carrer de la Barra de Ferro, 5",
    description: "Arte figurativo contemporáneo europeo en un palacete del XVIII. Conciertos en el patio.",
    url: "https://www.meam.es",
    tier: 2,
    lat: 41.3848,
    lng: 2.1808,
  },
  {
    id: "v-born-05",
    name: "Cal Pep",
    type: "restaurante",
    neighborhood: "El Born",
    address: "Plaça de les Olles, 8",
    description: "Barra de cocina marinera de mercado. Institución gastronómica desde 1986.",
    tier: 1,
    lat: 41.3840,
    lng: 2.1830,
  },

  // ─── Gótico ────────────────────────────────────────────────────────
  {
    id: "v-got-01",
    name: "MUHBA – Museu d'Història de Barcelona",
    type: "museo",
    neighborhood: "Gótico",
    address: "Plaça del Rei, s/n",
    description: "Ruinas romanas subterráneas de Barcino bajo la Plaça del Rei. Imprescindible.",
    url: "https://www.muhba.barcelona",
    tier: 1,
    lat: 41.3839,
    lng: 2.1772,
  },
  {
    id: "v-got-02",
    name: "Harlem Jazz Club",
    type: "sala de conciertos",
    neighborhood: "Gótico",
    address: "Carrer de la Comtessa de Sobradiel, 8",
    description: "Jazz, blues y soul en directo todas las noches. Club pequeño e íntimo.",
    tier: 2,
    lat: 41.3815,
    lng: 2.1766,
  },
  {
    id: "v-got-03",
    name: "Ocaña",
    type: "bar",
    neighborhood: "Gótico",
    address: "Plaça Reial, 13-15",
    description: "Coctelería y restaurante en la Plaça Reial. Terraza privilegiada y decoración ecléctica.",
    tier: 2,
    lat: 41.3801,
    lng: 2.1755,
  },
  {
    id: "v-got-04",
    name: "La Manual Alpargatera",
    type: "mercado",
    neighborhood: "Gótico",
    address: "Carrer d'Avinyó, 7",
    description: "Tienda artesana de alpargatas desde 1940. Icono del comercio tradicional del barrio.",
    tier: 3,
    lat: 41.3810,
    lng: 2.1770,
  },

  // ─── El Raval ──────────────────────────────────────────────────────
  {
    id: "v-rav-01",
    name: "MACBA",
    type: "museo",
    neighborhood: "El Raval",
    address: "Plaça dels Àngels, 1",
    description: "Museo de arte contemporáneo de Barcelona. Colección de arte de la segunda mitad del s. XX.",
    url: "https://www.macba.cat",
    tier: 1,
    lat: 41.3836,
    lng: 2.1672,
  },
  {
    id: "v-rav-02",
    name: "CCCB – Centre de Cultura Contemporània",
    type: "centro cultural",
    neighborhood: "El Raval",
    address: "Carrer de Montalegre, 5",
    description: "Centro de exposiciones, debates, festivales y cine. Patio interior espectacular.",
    url: "https://www.cccb.org",
    tier: 1,
    lat: 41.3838,
    lng: 2.1668,
  },
  {
    id: "v-rav-03",
    name: "Filmoteca de Catalunya",
    type: "cine",
    neighborhood: "El Raval",
    address: "Plaça de Salvador Seguí, 1-9",
    description: "Cine de repertorio, ciclos temáticos y archivo fílmico. Edificio de Josep Lluís Mateo.",
    url: "https://www.filmoteca.cat",
    tier: 1,
    lat: 41.3790,
    lng: 2.1698,
  },
  {
    id: "v-rav-04",
    name: "Bar Marsella",
    type: "bar",
    neighborhood: "El Raval",
    address: "Carrer de Sant Pau, 65",
    description: "Abierto desde 1820. Absenta, espejos viejos y fantasmas de Hemingway y Picasso.",
    tier: 1,
    lat: 41.3780,
    lng: 2.1710,
  },
  {
    id: "v-rav-05",
    name: "Bar Muy Buenas",
    type: "bar",
    neighborhood: "El Raval",
    address: "Carrer del Carme, 63",
    description: "Antigua farmacia reconvertida en bar con azulejos originales. Cócteles y vermut.",
    tier: 2,
    lat: 41.3822,
    lng: 2.1688,
  },
  {
    id: "v-rav-06",
    name: "La Confitería",
    type: "bar",
    neighborhood: "El Raval",
    address: "Carrer de Sant Pau, 128",
    description: "Coctelería en una antigua confitería con mobiliario original modernista.",
    tier: 2,
    lat: 41.3770,
    lng: 2.1695,
  },
  {
    id: "v-rav-07",
    name: "Antic Teatre",
    type: "teatro",
    neighborhood: "El Raval",
    address: "Carrer de Verdaguer i Callís, 12",
    description: "Teatro independiente con terraza-jardín escondida. Artes escénicas experimentales.",
    url: "https://www.anticteatre.com",
    tier: 2,
    lat: 41.3870,
    lng: 2.1740,
  },

  // ─── Eixample ──────────────────────────────────────────────────────
  {
    id: "v-eix-01",
    name: "L'Auditori",
    type: "auditorio",
    neighborhood: "Eixample",
    address: "Carrer de Lepant, 150",
    description: "Sede de la OBC. Música clásica, contemporánea y familiar. Diseño de Rafael Moneo.",
    url: "https://www.auditori.cat",
    tier: 1,
    lat: 41.3978,
    lng: 2.1823,
  },
  {
    id: "v-eix-02",
    name: "TNC – Teatre Nacional de Catalunya",
    type: "teatro",
    neighborhood: "Eixample",
    address: "Plaça de les Arts, 1",
    description: "Teatro nacional con 3 salas. Programación de dramaturgia catalana y clásicos universales.",
    url: "https://www.tnc.cat",
    tier: 1,
    lat: 41.3975,
    lng: 2.1840,
  },
  {
    id: "v-eix-03",
    name: "Fundació Antoni Tàpies",
    type: "museo",
    neighborhood: "Eixample",
    address: "Carrer d'Aragó, 255",
    description: "Arte contemporáneo en un edificio modernista de Domènech i Montaner. Colección permanente de Tàpies.",
    url: "https://fundaciotapies.org",
    tier: 1,
    lat: 41.3920,
    lng: 2.1637,
  },
  {
    id: "v-eix-04",
    name: "CaixaForum Barcelona",
    type: "centro cultural",
    neighborhood: "Eixample",
    address: "Avinguda de Francesc Ferrer i Guàrdia, 6-8",
    description: "Exposiciones de nivel internacional en la antigua fábrica Casaramona de Puig i Cadafalch.",
    url: "https://caixaforum.org/es/barcelona",
    tier: 1,
    lat: 41.3712,
    lng: 2.1490,
  },
  {
    id: "v-eix-05",
    name: "Cervecería Catalana",
    type: "restaurante",
    neighborhood: "Eixample",
    address: "Carrer de Mallorca, 236",
    description: "Tapas clásicas y barra siempre llena. Una de las cervecerías más populares de la ciudad.",
    tier: 2,
    lat: 41.3935,
    lng: 2.1620,
  },
  {
    id: "v-eix-06",
    name: "Dry Martini",
    type: "bar",
    neighborhood: "Eixample",
    address: "Carrer d'Aribau, 162",
    description: "Coctelería clásica con más de 80 años. Referencia mundial del dry martini.",
    tier: 1,
    lat: 41.3940,
    lng: 2.1540,
  },
  {
    id: "v-eix-07",
    name: "Galería Marlborough Barcelona",
    type: "galería",
    neighborhood: "Eixample",
    address: "Carrer d'Enric Granados, 68",
    description: "Galería de arte contemporáneo con artistas nacionales e internacionales.",
    url: "https://www.marlboroughgallery.com",
    tier: 2,
    lat: 41.3938,
    lng: 2.1580,
  },

  // ─── Barceloneta / Port ────────────────────────────────────────────
  {
    id: "v-bcn-01",
    name: "Paseo Marítimo de la Barceloneta",
    type: "espacio al aire libre",
    neighborhood: "Barceloneta / Port",
    address: "Passeig Marítim de la Barceloneta",
    description: "Paseo junto al mar desde el Hospital del Mar hasta el Port Olímpic. Esculturas y terrazas.",
    tier: 1,
    lat: 41.3780,
    lng: 2.1920,
  },
  {
    id: "v-bcn-02",
    name: "Arts Santa Mònica",
    type: "centro cultural",
    neighborhood: "Barceloneta / Port",
    address: "La Rambla, 7",
    description: "Centro de artes visuales y nuevos medios al final de la Rambla. Entrada libre.",
    url: "https://artssantamonica.gencat.cat",
    tier: 1,
    lat: 41.3768,
    lng: 2.1755,
  },
  {
    id: "v-bcn-03",
    name: "La Mar Salada",
    type: "restaurante",
    neighborhood: "Barceloneta / Port",
    address: "Passeig de Joan de Borbó, 58",
    description: "Arroces y cocina marinera en primera línea del puerto. Terraza con vistas.",
    tier: 2,
    lat: 41.3790,
    lng: 2.1845,
  },
  {
    id: "v-bcn-04",
    name: "Chiringuito Barceloneta",
    type: "chiringuito",
    neighborhood: "Barceloneta / Port",
    address: "Passeig Marítim de la Barceloneta, s/n",
    description: "Chiringuito clásico a pie de playa. Tapas, cócteles y atardeceres.",
    tier: 2,
    lat: 41.3775,
    lng: 2.1930,
  },
  {
    id: "v-bcn-05",
    name: "Museu Marítim de Barcelona",
    type: "museo",
    neighborhood: "Barceloneta / Port",
    address: "Avinguda de les Drassanes, s/n",
    description: "Historia naval en las Reales Atarazanas medievales. Galera real de Juan de Austria.",
    url: "https://www.mmb.cat",
    tier: 1,
    lat: 41.3753,
    lng: 2.1745,
  },

  // ─── Montjuïc ──────────────────────────────────────────────────────
  {
    id: "v-mon-01",
    name: "MNAC – Museu Nacional d'Art de Catalunya",
    type: "museo",
    neighborhood: "Montjuïc",
    address: "Palau Nacional, Parc de Montjuïc",
    description: "Mil años de arte catalán: románico, gótico, renacimiento, barroco y arte moderno. Vistas panorámicas.",
    url: "https://www.museunacional.cat",
    tier: 1,
    lat: 41.3685,
    lng: 2.1535,
  },
  {
    id: "v-mon-02",
    name: "Fundació Joan Miró",
    type: "museo",
    neighborhood: "Montjuïc",
    address: "Parc de Montjuïc, s/n",
    description: "La colección más completa de Miró. Edificio de Sert con terraza escultórica y vistas al mar.",
    url: "https://www.fmirobcn.org",
    tier: 1,
    lat: 41.3687,
    lng: 2.1600,
  },
  {
    id: "v-mon-03",
    name: "Teatre Grec",
    type: "teatro",
    neighborhood: "Montjuïc",
    address: "Passeig de Santa Madrona, 36",
    description: "Anfiteatro al aire libre sede del Festival Grec. Teatro, música y danza en verano.",
    url: "https://www.barcelona.cat/grec",
    tier: 1,
    lat: 41.3680,
    lng: 2.1585,
  },
  {
    id: "v-mon-04",
    name: "Jardins de Laribal",
    type: "jardín",
    neighborhood: "Montjuïc",
    address: "Passeig de Santa Madrona",
    description: "Jardines escalonados con fuentes árabes y pérgolas. Oasis escondido en Montjuïc.",
    tier: 2,
    lat: 41.3690,
    lng: 2.1575,
  },
  {
    id: "v-mon-05",
    name: "Jardí Botànic de Barcelona",
    type: "jardín",
    neighborhood: "Montjuïc",
    address: "Carrer del Doctor Font i Quer, 2",
    description: "Plantas mediterráneas de los cinco continentes. Diseño paisajístico contemporáneo.",
    url: "https://museuciencies.cat/jardi-botanic",
    tier: 2,
    lat: 41.3640,
    lng: 2.1500,
  },
  {
    id: "v-mon-06",
    name: "Poble Espanyol",
    type: "centro cultural",
    neighborhood: "Montjuïc",
    address: "Avinguda de Francesc Ferrer i Guàrdia, 13",
    description: "Museo al aire libre con réplicas arquitectónicas de toda España. Artesanos y gastronomía.",
    url: "https://www.poble-espanyol.com",
    tier: 1,
    lat: 41.3690,
    lng: 2.1470,
  },

  // ─── Sants / Poble-sec ────────────────────────────────────────────
  {
    id: "v-san-01",
    name: "Sala Apolo",
    type: "sala de conciertos",
    neighborhood: "Sants / Poble-sec",
    address: "Carrer Nou de la Rambla, 113",
    description: "Sala histórica de conciertos y club nocturno. Referencia de la noche barcelonesa desde 1943.",
    url: "https://www.sala-apolo.com",
    tier: 1,
    lat: 41.3738,
    lng: 2.1698,
  },
  {
    id: "v-san-02",
    name: "Hiroshima",
    type: "teatro",
    neighborhood: "Sants / Poble-sec",
    address: "Carrer de Vila i Vilà, 67",
    description: "Espacio multidisciplinar: artes escénicas, música experimental y residencias artísticas.",
    url: "https://www.hiroshima.cat",
    tier: 2,
    lat: 41.3725,
    lng: 2.1705,
  },
  {
    id: "v-san-03",
    name: "Teatre Lliure – Montjuïc",
    type: "teatro",
    neighborhood: "Sants / Poble-sec",
    address: "Plaça Margarida Xirgu, 1",
    description: "Sede principal del Teatre Lliure. Dos salas en el Palau de l'Agricultura.",
    url: "https://www.teatrelliure.com",
    tier: 1,
    lat: 41.3730,
    lng: 2.1660,
  },
  {
    id: "v-san-04",
    name: "Quimet & Quimet",
    type: "bar",
    neighborhood: "Sants / Poble-sec",
    address: "Carrer del Poeta Cabanyes, 25",
    description: "Montaditos y conservas en un bar minúsculo de cuarta generación. Culto absoluto.",
    tier: 1,
    lat: 41.3720,
    lng: 2.1685,
  },
  {
    id: "v-san-05",
    name: "Sala BARTS",
    type: "sala de conciertos",
    neighborhood: "Sants / Poble-sec",
    address: "Avinguda del Paral·lel, 62",
    description: "Sala de espectáculos con programación ecléctica: conciertos, humor, flamenco y danza.",
    url: "https://www.bfrfrts.cat",
    tier: 2,
    lat: 41.3745,
    lng: 2.1698,
  },
  {
    id: "v-san-06",
    name: "El Molino",
    type: "teatro",
    neighborhood: "Sants / Poble-sec",
    address: "Carrer de Vila i Vilà, 99",
    description: "Cabaret y music hall emblemático del Paral·lel, restaurado en 2010.",
    url: "https://www.elmolinobcn.com",
    tier: 2,
    lat: 41.3720,
    lng: 2.1700,
  },
  {
    id: "v-san-07",
    name: "Carrer de Blai",
    type: "espacio al aire libre",
    neighborhood: "Sants / Poble-sec",
    address: "Carrer de Blai",
    description: "Calle peatonal con decenas de bares de pintxos. El txoko de Barcelona.",
    tier: 1,
    lat: 41.3725,
    lng: 2.1670,
  },

  // ─── Sarrià / Pedralbes ───────────────────────────────────────────
  {
    id: "v-sar-01",
    name: "CosmoCaixa",
    type: "museo",
    neighborhood: "Sarrià / Pedralbes",
    address: "Carrer d'Isaac Newton, 26",
    description: "Museo de ciencia interactivo. Bosque inundado amazónico, planetario y exposiciones temporales.",
    url: "https://cosmocaixa.org",
    tier: 1,
    lat: 41.4131,
    lng: 2.1317,
  },
  {
    id: "v-sar-02",
    name: "Jardins del Palau de Pedralbes",
    type: "jardín",
    neighborhood: "Sarrià / Pedralbes",
    address: "Avinguda Diagonal, 686",
    description: "Jardines del antiguo palacio real con bambúes, fuente de Gaudí y conciertos de verano.",
    tier: 1,
    lat: 41.3875,
    lng: 2.1150,
  },
  {
    id: "v-sar-03",
    name: "Reial Monestir de Pedralbes",
    type: "museo",
    neighborhood: "Sarrià / Pedralbes",
    address: "Baixada del Monestir, 9",
    description: "Monasterio gótico del s. XIV con claustro de tres pisos. Murales de Ferrer Bassa.",
    url: "https://www.monfrfrpedralbes.barcelona",
    tier: 1,
    lat: 41.3957,
    lng: 2.1135,
  },
  {
    id: "v-sar-04",
    name: "Vivanda",
    type: "restaurante",
    neighborhood: "Sarrià / Pedralbes",
    address: "Carrer Major de Sarrià, 134",
    description: "Cocina catalana de proximidad en un caserón con terraza ajardinada.",
    tier: 2,
    lat: 41.3990,
    lng: 2.1210,
  },
  {
    id: "v-sar-05",
    name: "El Jardí de l'Àpat",
    type: "restaurante",
    neighborhood: "Sarrià / Pedralbes",
    address: "Carrer de Jaume Piquet, 23",
    description: "Restaurante con jardín escondido en el corazón de Sarrià. Cocina de temporada.",
    tier: 3,
    lat: 41.4000,
    lng: 2.1225,
  },
];

export function getVenuesByNeighborhood(neighborhood: string): Venue[] {
  return venues.filter((v) => v.neighborhood === neighborhood);
}

export function getVenuesByType(type: string): Venue[] {
  return venues.filter((v) => v.type === type);
}

export function getVenuesByTier(tier: 1 | 2 | 3): Venue[] {
  return venues.filter((v) => v.tier === tier);
}

export const NEIGHBORHOODS = [
  "Poblenou / 22@",
  "Gràcia",
  "El Born",
  "Gótico",
  "El Raval",
  "Eixample",
  "Barceloneta / Port",
  "Montjuïc",
  "Sants / Poble-sec",
  "Sarrià / Pedralbes",
] as const;
